title: Akash Nainani
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: ''
        url: ''
  header:
    bg: dark
    has_nav: true
    has_social: true
    profile_img: /images/webp.net-compress-image-1-.jpg
    tagline: A Problem Solver
    title: Akash Nainani
  layout_style: overflow
  palette: blue
disableKinds:
  - RSS
